# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_audited}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Brandon Keepers}]
  s.date = %q{2011-07-02}
  s.email = %q{brandon@opensoul.org}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "acts_as_audited.gemspec",
    "generators/audited_migration/USAGE",
    "generators/audited_migration/audited_migration_generator.rb",
    "generators/audited_migration/templates/migration.rb",
    "init.rb",
    "lib/acts_as_audited.rb",
    "lib/acts_as_audited/audit.rb",
    "lib/acts_as_audited/audit_sweeper.rb",
    "rails/init.rb",
    "test/acts_as_audited_test.rb",
    "test/audit_sweeper_test.rb",
    "test/audit_test.rb",
    "test/db/database.yml",
    "test/db/schema.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/collectiveidea/acts_as_audited}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{ActiveRecord extension that logs all revisions to your models in an audits table}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.7"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<trizle_client>, [">= 0"])
      s.add_runtime_dependency(%q<trizle_plugins>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.1"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<jnunemaker-matchy>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.7"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<trizle_client>, [">= 0"])
      s.add_dependency(%q<trizle_plugins>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 2.1"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<jnunemaker-matchy>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.7"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<trizle_client>, [">= 0"])
    s.add_dependency(%q<trizle_plugins>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 2.1"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<jnunemaker-matchy>, [">= 0"])
  end
end

